import express from 'express';
import employeeRoutes from './routes/employee.routes';
import salaryRoutes from './routes/salary.routes';
import metricsRoutes from './routes/metrics.routes';
import { errorHandler } from './middlewares/error-handler';
import 'dotenv/config';
const app = express();
app.use(express.json());
app.use('/employees', employeeRoutes);
app.use('/salary', salaryRoutes);
app.use('/metrics', metricsRoutes);
app.use(errorHandler);
export default app;